name: ci
on: [push, pull_request]

jobs:
  mac:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: prepare
        run: |
          brew update
          brew install erlang@23
      - name: install rebar3
        run: |
          wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
          cp ./rebar3 /usr/local/bin/rebar3
      - name: release build
        run: |
          make test

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.3.4.9, 23.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: ${{ matrix.otp }}
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.9'
      - name: release build with debug log off
        run: CMAKE_BUILD_TYPE=Release QUIC_ENABLE_LOGGING=OFF make test
